### ISSUE TITLE
データに変更がないとCIに失敗する

### ISSUE THREAD

**Issue by circled9** [CodeForNiigata/covid19-data-niigata#1]
CIの内部でgitのcommitをやっているが、ファイルに変更がないとCI自体が失敗扱いになる。

本質的には失敗ではなく、またPDFのフォーマットが変わったなどの失敗と区別がつかないので、ファイルに変更がない場合もCIを成功扱いにしたい。

https://github.com/CodeForNiigata/covid19-data-niigata/actions/runs/80629514

**Comment by NPoi** [comment]
以下の判断をどうするかってありますか？
「Actions画面の結果表示」以外に考えないでいいのかなと思っていて、その確認なのですが。

- 変更があって成功
- 変更がなくて成功
- 失敗
    - フォーマットが変わった
    - ファイルが取得できなかった
    - その他

**Comment by circled9** [comment]
pythonの範囲でエラーが出たら失敗、そうじゃない場合は成功という雑な判断でいいと思います。

という前提で...
どっかのサイトを見て見様見真似で`git push origin master || true` ってやってます。
gitのpushの成否にかかわらず成功させるコードですね。（多分）
同様にcommitに`|| true`を末尾に追加してあげるだけでよさそうです。
