### ISSUE TITLE
対策側サイト　レイアウト変更によるデータフォーマットの変更

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19-data-niigata#13]
検査実施件数を以下の通り色分けする対応（covid19 PR328）の結果data.jsonのフォーマットが変更になりましたのでどこかのタイミングで変更をお願いしたく。
![image](https://user-images.githubusercontent.com/14312281/81828481-c90c6880-9574-11ea-8197-d9241698c11c.png)

data.jsonの右が現状、左が更新後です。
![image](https://user-images.githubusercontent.com/14312281/81828357-ada15d80-9574-11ea-89f5-2956aec45ac8.png)

**Comment by NPoi** [comment]
@michiyac4ngt これって、左側って、小計がゼロでも日付入りますよね？

**Comment by michiyac4ngt** [comment]
いります。
